AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Nested stack
Resources:
 MyWebserverstack1:
   Type: AWS::CloudFormation::Stack
   Properties:
       TemplateURL: https://s3.amazonaws.com/whizlabs.36216.28116953/Nested_ASG.yaml
       TimeoutInMinutes: '5'
       Parameters:
         LoadBalancerName: !GetAtt 'Elbstack.Outputs.LoadBalancerName'
 Elbstack:
   Type: AWS::CloudFormation::Stack
   Properties:
      TemplateURL: https://s3.amazonaws.com/whizlabs.36216.28116953/Nested_LB.yaml
Outputs:
  StackRef:
    Value: !Ref Elbstack 
  OutputFromNestedStack:
    Value: !GetAtt Elbstack.Outputs.LoadBalancerName